name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # setiap hari
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate github-contribution-grid-snake.svg

    steps:
      - uses: actions/checkout@v3

      - name: generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: imZaaa
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: push svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
